title: Claudio Faoro

permalink: pretty

timezone: "Europa/Rome"
url: https://claudiofaoro.com
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-polyglot

# Polyglot Settings
languages: ["it", "en"]
default_lang: "it"
exclude_from_localization: ["css", "images", "js", "sitemap.xml"]
parallel_localization: false
lang_from_path: true

sass:
  sourcemap: never
